### ISSUE TITLE
Channel name not accurate anymore

### ISSUE THREAD

**Issue by abcdan** [lukasvdberk/vakantie-vincent-discord-bot#1]
> A discord bot that will send a video every day from the channel "moet jij weten productions". This person has a character callled vakantie vincent and he is very weird and funny.

It's not longer "moet jij weten productions"

**Comment by lukasvdberk** [comment]
It is not?

**Comment by lukasvdberk** [comment]
That really sucks.....

**Comment by abcdan** [comment]
fixen

**Comment by abcdan** [comment]
nu

**Comment by lukasvdberk** [comment]
nee balsam

**Comment by abcdan** [comment]
jawel

**Comment by lukasvdberk** [comment]
done balsam https://github.com/lukasvdberk/vakantie-vincent-discord-bot/blob/master/README.md

**Comment by abcdan** [comment]
ok
